version: "3"

services:
  my_app:
    build: .
    env_file:
      - .env
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn my_app.wsgi:my_application  -b 0.0.0.0:8000"
    container_name: my_app
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  my_app_nginx:
    build: ./nginx
    restart: always
    container_name: my_app_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entrypoints=web"
      - "traefik.http.routers.my_app_nginx.rule=Host(`my_app.localhost`)"
      - "traefik.http.services.my_app_nginx.loadbalancer.server.port=80"
    volumes:
      - ./app:/usr/src/app
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - my_app

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes: 
    postgdata: